#!/bin/bash

while [ -n "$1" ]
do
case "$1" in
-g) read -p "Git check:" gitcheck
git clone $gitcheck 
shift ;;
esac
done

usernow=`whoami`
pathsis=`pwd`

read -p "Day check:" daycheck

cd $usernow

listex=`ls`

echo -e
echo "Find directory: $listex"
echo -e

for file in $listex
do
cd $file
if [ -f $pathsis/$daycheck/$file/ft_putchar.c ]
then
	fttest=`find . -name 'ft*.c'`
	cp $pathsis/$daycheck/$file/ft_putchar.c ft_putchar.c
	cp $pathsis/$daycheck/$file/main.c main.c
	gcc -Wall -Wextra -Werror main.c ft_putchar.c $fttest -o test
	echo -e "Directory:  $file"
	echo -e "Return: `./test`"
else
	cp $pathsis/$daycheck/$file/main.c main.c
	fttest=`find . -name 'ft*.c'`
	gcc -Wall -Wextra -Werror main.c $fttest -o test
	echo -e "Directory: $file"
	echo -e "Return: `./test`"
fi
echo -e "Norminette: `norminette -R CheckForbiddenSourceHeader $fttest`"
echo -e
cd ..
done
